import { Color } from 'three';
import type { CelestialBody } from '@/types/planet';

export const NASA_API_KEY = 'CH3TuB34hg317ulEggcZCMlKgCCPYQeTzdzJDNCz';

export const GEMINI_MODEL = 'gemini-2.5-flash';

export const AU_TO_SCENE = 15;

export const celestialBodies: CelestialBody[] = [
  {
    name: 'Mercúrio',
    size: 0.5,
    dist: 8,
    speed: 0.0041,
    initialAngle: 2.1,
    texture: 'mercury.jpg',
    roughness: 1,
    metalness: 0.02,
    type: 'planet',
    info: "Planeta mais próximo do Sol. Temperaturas superficiais variam de -173°C a 427°C. Não possui atmosfera nem luas.",
    discoveryYear: 'Ancient',
    moons: [],
  },
  {
    name: 'Vênus',
    size: 0.9,
    dist: 11,
    speed: 0.0016,
    initialAngle: 4.8,
    texture: 'venus.jpg',
    roughness: 0.6,
    metalness: 0.05,
    type: 'planet',
    info: "Planeta mais quente do nosso sistema solar com temperaturas superficiais de 462°C. Possui uma atmosfera espessa e tóxica de dióxido de carbono.",
    discoveryYear: 'Ancient',
    moons: [],
  },
  {
    name: 'Terra',
    size: 1,
    dist: 15,
    speed: 0.001,
    initialAngle: 3.45,
    texture: 'earth.jpg',
    roughness: 0.5,
    metalness: 0.01,
    type: 'planet',
    info: 'O único planeta conhecido com vida. 71% da superfície coberta por água. Possui um satélite natural.',
    discoveryYear: 'N/A',
    moons: [
      {
        name: 'Lua',
        size: 0.27,
        dist: 2.5,
        speed: 0.037,
        color: new Color(0.53, 0.53, 0.53),
        info: "Único satélite natural da Terra. Formado há 4,5 bilhões de anos.",
        initialAngle: 1.2,
      },
    ],
  },
  {
    name: 'Marte',
    size: 0.8,
    dist: 19,
    speed: 0.00053,
    initialAngle: 0.9,
    texture: 'mars.jpg',
    roughness: 0.75,
    metalness: 0.02,
    type: 'planet',
    info: 'O Planeta Vermelho. Possui o maior vulcão (Monte Olimpo) e o maior cânion (Valles Marineris) do sistema solar.',
    discoveryYear: 'Ancient',
    moons: [
      {
        name: 'Fobos',
        size: 0.05,
        dist: 1.5,
        speed: 0.32,
        color: new Color(0.4, 0.26, 0.13),
        info: 'Maior lua de Marte. Orbita Marte 3 vezes por dia.',
        initialAngle: 0.5,
      },
      {
        name: 'Deimos',
        size: 0.03,
        dist: 2.2,
        speed: 0.08,
        color: new Color(0.4, 0.26, 0.13),
        info: "Lua menor e externa de Marte. Leva 30 horas para orbitar Marte.",
        initialAngle: 2.1,
      },
    ],
  },
  {
    name: 'Vesta',
    size: 0.15,
    dist: 20.5,
    speed: 0.00029,
    initialAngle: 5.2,
    color: new Color(0.8, 0.8, 0.8),
    roughness: 1.0,
    metalness: 0.1,
    type: 'asteroid',
    info: 'Segundo maior asteroide. Possui interior diferenciado com superfície basáltica. Visitado pela sonda Dawn.',
    discoveryYear: '1807',
    moons: [],
  },
  {
    name: 'Palas',
    size: 0.12,
    dist: 21.2,
    speed: 0.00022,
    initialAngle: 1.8,
    color: new Color(0.67, 0.67, 0.67),
    roughness: 1.0,
    metalness: 0.05,
    type: 'asteroid',
    info: 'Terceiro maior asteroide. Órbita altamente inclinada. Possivelmente um protoplaneta.',
    discoveryYear: '1802',
    moons: [],
  },
  {
    name: 'Júpiter',
    size: 2,
    dist: 25,
    speed: 0.000084,
    initialAngle: 2.7,
    texture: 'jupiter.jpg',
    roughness: 0.9,
    metalness: 0.0,
    type: 'planet',
    info: 'Maior planeta do nosso sistema solar. A Grande Mancha Vermelha é uma tempestade maior que a Terra. Possui 95 luas conhecidas.',
    discoveryYear: 'Ancient',
    moons: [
      {
        name: 'Io',
        size: 0.15,
        dist: 3.5,
        speed: 0.56,
        color: new Color(1.0, 1.0, 0.6),
        info: 'Corpo mais vulcanicamente ativo do sistema solar.',
        initialAngle: 0.8,
      },
      {
        name: 'Europa',
        size: 0.13,
        dist: 4.2,
        speed: 0.28,
        color: new Color(0.53, 0.81, 0.92),
        info: 'Lua coberta de gelo com oceano subsuperficial. Potencial para vida.',
        initialAngle: 1.5,
      },
      {
        name: 'Ganimedes',
        size: 0.22,
        dist: 5.1,
        speed: 0.14,
        color: new Color(0.55, 0.49, 0.42),
        info: 'Maior lua do sistema solar. Possui seu próprio campo magnético.',
        initialAngle: 3.2,
      },
      {
        name: 'Calisto',
        size: 0.20,
        dist: 6.0,
        speed: 0.06,
        color: new Color(0.41, 0.41, 0.41),
        info: 'Corpo mais craterado do sistema solar.',
        initialAngle: 4.9,
      },
    ],
  },
  {
    name: 'Saturno',
    size: 1.7,
    dist: 31,
    speed: 0.000034,
    initialAngle: 5.8,
    texture: 'saturn.jpg',
    hasRings: true,
    roughness: 0.9,
    metalness: 0.0,
    type: 'planet',
    info: 'Famoso por seu proeminente sistema de anéis. Menos denso que a água. Possui 146 luas conhecidas.',
    discoveryYear: 'Ancient',
    moons: [
      {
        name: 'Mimas',
        size: 0.06,
        dist: 2.8,
        speed: 1.05,
        color: new Color(0.7, 0.7, 0.7),
        info: 'Aparência semelhante à Estrela da Morte com a gigante cratera Herschel.',
        initialAngle: 0.9,
      },
      {
        name: 'Encélado',
        size: 0.08,
        dist: 3.2,
        speed: 0.73,
        color: new Color(0.94, 0.97, 1.0),
        info: 'Gêiseres de gelo do polo sul. Oceano subsuperficial.',
        initialAngle: 4.1,
      },
      {
        name: 'Titã',
        size: 0.21,
        dist: 5.5,
        speed: 0.063,
        color: new Color(1.0, 0.65, 0.0),
        info: 'Possui atmosfera espessa e lagos de metano líquido.',
        initialAngle: 2.3,
      },
    ],
  },
  {
    name: 'Urano',
    size: 1.2,
    dist: 37,
    speed: 0.000012,
    initialAngle: 1.2,
    texture: 'uranus.jpg',
    roughness: 0.85,
    metalness: 0.0,
    type: 'planet',
    info: 'Gigante de gelo inclinado de lado (inclinação axial de 98°). Possui anéis fracos e 28 luas conhecidas.',
    discoveryYear: '1781',
    moons: [
      {
        name: 'Ariel',
        size: 0.08,
        dist: 2.2,
        speed: 0.39,
        color: new Color(0.6, 0.6, 0.65),
        info: 'Superfície mais jovem entre as luas de Urano com vales de falha.',
        initialAngle: 2.1,
      },
      {
        name: 'Titania',
        size: 0.11,
        dist: 3.0,
        speed: 0.12,
        color: new Color(0.55, 0.55, 0.6),
        info: 'Maior lua de Urano com cânions profundos.',
        initialAngle: 1.7,
      },
    ],
  },
  {
    name: 'Netuno',
    size: 1.1,
    dist: 42,
    speed: 0.0000061,
    initialAngle: 6.1,
    texture: 'neptune.jpg',
    roughness: 0.85,
    metalness: 0.0,
    type: 'planet',
    info: 'Planeta mais ventoso com velocidades de até 2.100 km/h. Cor azul profunda devido ao metano na atmosfera.',
    discoveryYear: '1846',
    moons: [
      {
        name: 'Tritão',
        size: 0.11,
        dist: 3.0,
        speed: 0.17,
        color: new Color(0.53, 0.81, 0.92),
        info: 'Maior lua de Netuno. Orbita em sentido retrógrado. Gêiseres de nitrogênio.',
        initialAngle: 0.9,
      },
    ],
  },
  {
    name: 'Ceres',
    size: 0.3,
    dist: 22,
    speed: 0.00022,
    initialAngle: 0,
    color: new Color(0.6, 0.6, 0.6),
    roughness: 1.0,
    metalness: 0.0,
    type: 'dwarf',
    info: 'Maior objeto do cinturão de asteroides. Possui gelo de água e possível oceano subsuperficial. Visitado pela sonda Dawn.',
    discoveryYear: '1801',
    moons: [],
  },
  {
    name: 'Plutão',
    size: 0.4,
    dist: 48,
    speed: 0.000004,
    initialAngle: 5.3,
    color: new Color(0.82, 0.71, 0.55),
    roughness: 1.0,
    metalness: 0.0,
    type: 'dwarf',
    info: 'Planeta anão com geleira em forma de coração. Possui 5 luas conhecidas. Visitado pela New Horizons em 2015.',
    discoveryYear: '1930',
    moons: [
      {
        name: 'Caronte',
        size: 0.2,
        dist: 1.2,
        speed: 0.16,
        color: new Color(0.6, 0.6, 0.6),
        info: 'Maior lua de Plutão. Forma sistema binário com Plutão.',
        initialAngle: 2.1,
      },
    ],
  },
];

